SSAnne_2F_Room5_Frlg_MapScripts::
	.byte 0

SSAnne_2F_Room5_EventScript_Gentleman::
	msgbox SSAnne_2F_Room5_Text_HaveYouGoneToSafariZone, MSGBOX_NPC
	end

SSAnne_2F_Room5_EventScript_LittleBoy::
	msgbox SSAnne_2F_Room5_Text_WeThinkSafariZoneIsAwesome, MSGBOX_NPC
	end

SSAnne_2F_Room5_Text_HaveYouGoneToSafariZone::
	.string "Folk call CINNABAR the\n"
	.string "sea's gateway.\p"
	.string "Pah. VERMILION's the true\n"
	.string "port. Clean these days…\p"
	.string "Wasn't always.$"

SSAnne_2F_Room5_Text_WeThinkSafariZoneIsAwesome::
	.string "Me and Dad rode the whole\n"
	.string "SAFARI ZONE!\p"
	.string "I wanna go back the second\n"
	.string "we land…$"

