SSAnne_2F_Room5_Frlg_MapScripts::
	.byte 0

SSAnne_2F_Room5_EventScript_Gentleman::
	msgbox SSAnne_2F_Room5_Text_HaveYouGoneToSafariZone, MSGBOX_NPC
	end

SSAnne_2F_Room5_EventScript_LittleBoy::
	msgbox SSAnne_2F_Room5_Text_WeThinkSafariZoneIsAwesome, MSGBOX_NPC
	end

SSAnne_2F_Room5_Text_HaveYouGoneToSafariZone::
	.string "You'll hear folk swear CINNABAR is\n"
	.string "the gateway to the sea.\p"
	.string "Pah. VERMILION is the true port,\n"
	.string "and a clean one these days.\p"
	.string "Runs proud, that harbor. Wasn't\n"
	.string "always so, mind.$"

SSAnne_2F_Room5_Text_WeThinkSafariZoneIsAwesome::
	.string "Me and my dad rode all through the\n"
	.string "SAFARI ZONE!\p"
	.string "I wanna go straight back the second\n"
	.string "we step off this boat.$"

