SafariZone_West_RestHouse_Frlg_MapScripts::
	.byte 0

SafariZone_West_RestHouse_EventScript_Man::
	msgbox SafariZone_West_Text_BaitMakesMonStickAround, MSGBOX_NPC
	end

SafariZone_West_RestHouse_EventScript_Scientist::
	msgbox SafariZone_West_Text_RocksMakeMonRunButEasierCatch, MSGBOX_NPC
	end

SafariZone_West_RestHouse_EventScript_CooltrainerF::
	msgbox SafariZone_West_Text_HikedLotsDidntSeeMonIWanted, MSGBOX_NPC
	end

SafariZone_West_Text_KogaPatrolsSafariEverySoOften::
	.string "The SAFARI ZONE's huge, wouldn't\n"
	.string "you say?\p"
	.string "FUCHSIA's GYM LEADER, KOGA, \n"
	.string "patrols the grounds every so often.\p"
	.string "Thanks to him, we can play here\n"
	.string "knowing that we're safe.$"

SafariZone_West_Text_RocksMakeMonRunButEasierCatch::
	.string "Pelt a POKéMON with a ROCK\n"
	.string "and it may bolt, but it'll be\l"
	.string "far easier to catch after.$"

SafariZone_West_Text_BaitMakesMonStickAround::
	.string "Toss out some BAIT and a\n"
	.string "POKéMON may linger to eat,\l"
	.string "staying put a good while.$"

SafariZone_West_Text_HikedLotsDidntSeeMonIWanted::
	.string "Hiked all day. Threw BAIT,\n"
	.string "threw ROCKS. Caught nothing.\p"
	.string "Old-timers tell of a walker\n"
	.string "who crossed KANTO with an\l"
	.string "empty belt…\p"
	.string "and the wild ones just\n"
	.string "followed him. No BALLS at all.\p"
	.string "…Maybe I've got it backward.$"

