SafariZone_West_RestHouse_Frlg_MapScripts::
	.byte 0

SafariZone_West_RestHouse_EventScript_Man::
	msgbox SafariZone_West_Text_BaitMakesMonStickAround, MSGBOX_NPC
	end

SafariZone_West_RestHouse_EventScript_Scientist::
	msgbox SafariZone_West_Text_RocksMakeMonRunButEasierCatch, MSGBOX_NPC
	end

SafariZone_West_RestHouse_EventScript_CooltrainerF::
	msgbox SafariZone_West_Text_HikedLotsDidntSeeMonIWanted, MSGBOX_NPC
	end

SafariZone_West_Text_KogaPatrolsSafariEverySoOften::
	.string "The SAFARI ZONE's huge, wouldn't\n"
	.string "you say?\p"
	.string "FUCHSIA's GYM LEADER, KOGA, \n"
	.string "patrols the grounds every so often.\p"
	.string "Thanks to him, we can play here\n"
	.string "knowing that we're safe.$"

SafariZone_West_Text_RocksMakeMonRunButEasierCatch::
	.string "Throw a ROCK and it may bolt,\n"
	.string "but it's easier to catch.$"

SafariZone_West_Text_BaitMakesMonStickAround::
	.string "Throw BAIT and a POKéMON\n"
	.string "may linger to eat.$"

SafariZone_West_Text_HikedLotsDidntSeeMonIWanted::
	.string "Hiked all day. BAIT, ROCKS,\n"
	.string "nothing to show.\p"
	.string "They tell of a walker who\n"
	.string "crossed KANTO, belt empty…\p"
	.string "and the wild ones followed.$"

