gFameCheckerFlavorText_ProfOak0:: @ 0x81AD106
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}OAK POKéMON RESEARCH LAB$"

gFameCheckerFlavorText_ProfOak1:: @ 0x81AD145
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}A complete guide to every POKéMON\n"
	.string "in the world. Every last one.\p"
	.string "That was my dream. …No gaps.\n"
	.string "I cannot abide the gaps.$"

gFameCheckerFlavorText_ProfOak2:: @ 0x81AD1BB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}PROF. OAK may not look like much,\n"
	.string "but he's the authority on POKéMON.\p"
	.string "Many POKéMON TRAINERS hold him in\n"
	.string "high regard.$"

gFameCheckerFlavorText_ProfOak3:: @ 0x81AD258
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}PROF. OAK reportedly lives with his\n"
	.string "grandchildren, DAISY and {RIVAL}.$"

gFameCheckerFlavorText_ProfOak4:: @ 0x81AD2B9
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I hear OAK fusses over you, child.\p"
	.string "I knew him when he was tough.\n"
	.string "When he was DANGEROUS.\p"
	.string "Now he presses POKéMON into a book.\n"
	.string "…He chose that. I did not.$"

gFameCheckerFlavorText_ProfOak5:: @ 0x81AD377
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}PROF. OAK is going to have his own\n"
	.string "radio show soon.\p"
	.string "The program will be called PROF.\n"
	.string "OAK'S POKéMON SEMINAR.$"

gFameCheckerFlavorText_Daisy0:: @ 0x81AD40C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}If you show DAISY your POKéMON,\n"
	.string "she can tell how much it likes you.\p"
	.string "Occasionally, she will even groom\n"
	.string "a POKéMON for you.$"

gFameCheckerFlavorText_Daisy1:: @ 0x81AD4AE
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}But the person who is most liked by\n"
	.string "POKéMON is DAISY, I think.$"

gFameCheckerFlavorText_Daisy2:: @ 0x81AD516
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}She was gently grooming POKéMON…\n"
	.string "She was a little angel.\p"
	.string "That little girl's name…\n"
	.string "I think it was DAISY.$"

gFameCheckerFlavorText_Daisy3:: @ 0x81AD5A7
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}PROF. OAK reportedly lives with his\n"
	.string "grandchildren, DAISY and {RIVAL}.$"

gFameCheckerFlavorText_Daisy4:: @ 0x81AD608
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}A girl from PALLET TOWN, DAISY,\n"
	.string "she enjoys TEA every day.\p"
	.string "She visits the CELADON DEPT. STORE\n"
	.string "to buy some TEA.$"

gFameCheckerFlavorText_Daisy5:: @ 0x81AD69F
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}The Spring POKéMON CONTEST's\n"
	.string "Grand Champion is DAISY OAK of\l"
	.string "PALLET TOWN!$"

gFameCheckerFlavorText_Brock0:: @ 0x81AD705
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}PEWTER CITY POKéMON GYM\n"
	.string "LEADER: BROCK\l"
	.string "The Rock-Solid Romantic!$"

gFameCheckerFlavorText_Brock1:: @ 0x81AD771
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}My POKéMON are ROCK hard, and\n"
	.string "ROCK never lets a man down.\p"
	.string "People do. …ROCK doesn't.\n"
	.string "That is why I train the ROCK type.$"

gFameCheckerFlavorText_Brock2:: @ 0x81AD840
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BROCK runs that GYM day and\n"
	.string "night, and takes every challenger.\p"
	.string "Some say he needs the fees.\n"
	.string "He says it's for love of the ROCK.$"

gFameCheckerFlavorText_Brock3:: @ 0x81AD908
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BROCK's got a heart bigger than\n"
	.string "MT. MOON. Everybody loves him.\p"
	.string "Trouble is, he loves right back.\n"
	.string "…Every time. And it costs him.$"

gFameCheckerFlavorText_Brock4:: @ 0x81AD99A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I dig fossils here under\n"
	.string "MT. MOON. BROCK lends a hand.\p"
	.string "Hard to reach him lately, though.\n"
	.string "His phones never stop ringing.$"

gFameCheckerFlavorText_Brock5:: @ 0x81ADA27
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Each phone in BROCK's GYM rings\n"
	.string "its own tune, they say.\p"
	.string "He calls it his filing system.\n"
	.string "One ring per… previous sponsor.$"

gFameCheckerFlavorText_Misty0:: @ 0x81ADA91
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}CERULEAN CITY POKéMON GYM\n"
	.string "LEADER: MISTY\l"
	.string "The Fighting Sensational Sister!$"

gFameCheckerFlavorText_Misty1:: @ 0x81ADAF6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}My policy is all-out offense with\n"
	.string "WATER POKéMON.\p"
	.string "WATER types stay in the pool.\n"
	.string "They never wander off on you.$"

gFameCheckerFlavorText_Misty2:: @ 0x81ADB5A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}MISTY runs this GYM alone, and\n"
	.string "has for years.\p"
	.string "Her sisters do the water shows.\n"
	.string "The battling? That is all her.$"

gFameCheckerFlavorText_Misty3:: @ 0x81ADBD9
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Strong TRAINERS and WATER POKéMON\n"
	.string "fill these parts.\p"
	.string "They say MISTY trains here, and\n"
	.string "her PSYDUCK answers to no one.$"

gFameCheckerFlavorText_Misty4:: @ 0x81ADC72
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}This cape is a famous date spot.\p"
	.string "MISTY comes here to think, they say.\n"
	.string "…Always with that PSYDUCK in tow.$"

gFameCheckerFlavorText_Misty5:: @ 0x81ADCEB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}The CERULEAN GYM keeps one strict\n"
	.string "rule at its door.\p"
	.string "No BUG POKéMON past it. Not one.\n"
	.string "…No one dares ask MISTY why.$"

gFameCheckerFlavorText_LtSurge0:: @ 0x81ADD3C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}VERMILION CITY POKéMON GYM\n"
	.string "LEADER: LT. SURGE\l"
	.string "The Lightning Lieutenant!$"

gFameCheckerFlavorText_LtSurge1:: @ 0x81ADDA7
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Electric POKéMON pulled me through\n"
	.string "the war, kid.\p"
	.string "Freed 'em from a bad spot once.\n"
	.string "They've had my back ever since.$"

gFameCheckerFlavorText_LtSurge2:: @ 0x81ADE0B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I served under the LT. Hardest\n"
	.string "CO I ever knew.\p"
	.string "He drills you till you can't quit.\n"
	.string "That GYM is a trial, not a fight.$"

gFameCheckerFlavorText_LtSurge3:: @ 0x81ADE82
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Some of us knew the LT before\n"
	.string "the stripes.\p"
	.string "Back when they just called him\n"
	.string "'Private.' He came up from nothing.$"

gFameCheckerFlavorText_LtSurge4:: @ 0x81ADEEC
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}The LT rigged that GYM himself.\n"
	.string "Switches, locks, the works.\p"
	.string "Not cruelty. Discipline.\n"
	.string "He wants to see if you'll quit.$"

gFameCheckerFlavorText_LtSurge5:: @ 0x81ADF6A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}They say the LT once sailed on\n"
	.string "the S.S. ANNE.\p"
	.string "Struck lightning-fast one night, and\n"
	.string "VERMILION has been free ever since.$"

gFameCheckerFlavorText_Erika0:: @ 0x81AE009
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}CELADON CITY POKéMON GYM\n"
	.string "LEADER: ERIKA\l"
	.string "The Sleeping Enigma!$"

gFameCheckerFlavorText_Erika1:: @ 0x81AE072
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I tend flowers found nowhere else\n"
	.string "in all of KANTO.\p"
	.string "Some soothe. Some sting.\n"
	.string "…Even I lose track of which.$"

gFameCheckerFlavorText_Erika2:: @ 0x81AE0F3
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Our LEADER ERIKA is famous, and\n"
	.string "no two of us tell it the same.\p"
	.string "Ask ten of us her story.\n"
	.string "You will hear of ten ERIKAs.$"

gFameCheckerFlavorText_Erika3:: @ 0x81AE15B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Our GYM is full of women, and\n"
	.string "ERIKA welcomes every one.\p"
	.string "Some come to learn her flowers.\n"
	.string "Some come to be left alone.\p"
	.string "Where they came from, she never\n"
	.string "asks. …That is her way.$"

gFameCheckerFlavorText_Erika4:: @ 0x81AE1E5
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}My blossoms carry a scent found\n"
	.string "nowhere else.\p"
	.string "It calms a whole city, some say.\n"
	.string "…Others say never breathe twice.$"

gFameCheckerFlavorText_Erika5:: @ 0x81AE247
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Peek into CELADON GYM and you'll\n"
	.string "find ERIKA fast asleep.\p"
	.string "No one has ever seen her wake.\n"
	.string "…No one is sure that she does.$"

gFameCheckerFlavorText_Koga0:: @ 0x81AE2B6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}FUCHSIA CITY POKéMON GYM\n"
	.string "LEADER: KOGA\l"
	.string "The Poison Power Baron!$"

gFameCheckerFlavorText_Koga1:: @ 0x81AE31D
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Despair before the creeping horror\n"
	.string "of POISON POKéMON!\p"
	.string "My WEEZING never rest. Nor do the\n"
	.string "fires that light this whole land.$"

gFameCheckerFlavorText_Koga2:: @ 0x81AE37D
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}KOGA hired me for the old trade.\n"
	.string "Misdirection. Sleight of hand.\p"
	.string "The costume, the maze… Look here,\n"
	.string "so you don't look there.$"

gFameCheckerFlavorText_Koga3:: @ 0x81AE407
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}My father is the GYM LEADER of\n"
	.string "this town.\p"
	.string "He keeps the lights on for all of\n"
	.string "KANTO. They should thank him.\p"
	.string "…He says so himself.$"

gFameCheckerFlavorText_Koga4:: @ 0x81AE48D
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}KOGA INDUSTRIES never sleeps,\n"
	.string "they say.\p"
	.string "Its stacks foul FUCHSIA's air.\n"
	.string "Its power runs every home. Both true.$"

gFameCheckerFlavorText_Koga5:: @ 0x81AE51B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}The SAFARI ZONE is the last green\n"
	.string "place left near FUCHSIA.\p"
	.string "KOGA's smoke creeps nearer each\n"
	.string "year. …Yet his money funds it.\p"
	.string "We bite the hand, and feed from it.$"

gFameCheckerFlavorText_Sabrina0:: @ 0x81AE5E8
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}SAFFRON CITY POKéMON GYM\n"
	.string "LEADER: SABRINA\l"
	.string "The Girl Who Went Cold!$"

gFameCheckerFlavorText_Sabrina1:: @ 0x81AE656
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}You know the girl LEADER in\n"
	.string "SAFFRON CITY?\p"
	.string "PSYCHIC POKéMON, they say.\n"
	.string "And folk who cross her… vanish.$"

gFameCheckerFlavorText_Sabrina2:: @ 0x81AE6D7
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}My gift came when I was a child,\n"
	.string "and it grew past me.\p"
	.string "To cage it, I let my heart go\n"
	.string "cold. …It has been quiet since.$"

gFameCheckerFlavorText_Sabrina3:: @ 0x81AE762
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I do not battle for sport.\p"
	.string "All of SAFFRON rests quiet within\n"
	.string "me. A small, still place.\p"
	.string "Step inside, and I will show you.$"

gFameCheckerFlavorText_Sabrina4:: @ 0x81AE7CB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}They say SABRINA keeps people.\n"
	.string "Inside dolls.\p"
	.string "COPYCAT found one warm to the\n"
	.string "touch. …Dolls should be cold.$"

gFameCheckerFlavorText_Sabrina5:: @ 0x81AE841
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}SABRINA wiped out the KARATE\n"
	.string "MASTER next door without a word.\p"
	.string "Hard to think she once laughed\n"
	.string "like a bell. …What became of her?$"

gFameCheckerFlavorText_Blaine0:: @ 0x81AE89E
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}CINNABAR ISLAND POKéMON GYM\n"
	.string "LEADER: BLAINE\l"
	.string "The Man Who Plays With Fire!$"

gFameCheckerFlavorText_Blaine1:: @ 0x81AE90A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}My FIRE POKéMON burn hotter than\n"
	.string "any challenger can bear!\p"
	.string "I have seen fire warm a home…\n"
	.string "and swallow one whole. Mind it.$"

gFameCheckerFlavorText_Blaine2:: @ 0x81AE990
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Our LEADER BLAINE tests your mind\n"
	.string "before your POKéMON.\p"
	.string "Raw power without wisdom, he says,\n"
	.string "once made a monster.\p"
	.string "…He never says more than that.$"

gFameCheckerFlavorText_Blaine3:: @ 0x81AEA59
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BLAINE lived on this island long\n"
	.string "before the LAB was built.\p"
	.string "He was a scientist then. A brilliant\n"
	.string "one. …He does not speak of it.$"

gFameCheckerFlavorText_Blaine4:: @ 0x81AEAEE
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}It's a photo of BLAINE and\n"
	.string "MR. FUJI. Younger. Unburned.\p"
	.string "Two friends who once made\n"
	.string "something they could not unmake.$"

gFameCheckerFlavorText_Blaine5:: @ 0x81AEB69
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}They say BLAINE took the GYM after\n"
	.string "the old MANSION burned.\p"
	.string "Some say he lit it himself.\n"
	.string "…Some say he could not stop it.$"

gFameCheckerFlavorText_Lorelei0:: @ 0x81AEBDF
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I am LORELEI of the ELITE FOUR.$"

gFameCheckerFlavorText_Lorelei1:: @ 0x81AEC28
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}They call ICE the weakest type.\p"
	.string "I have given my life to proving\n"
	.string "them wrong.$"

gFameCheckerFlavorText_Lorelei2:: @ 0x81AEC82
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Where was this person born?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}We've had a great and powerful\n"
	.string "TRAINER grow up on this island.\p"
	.string "I bet even you'd know her.\n"
	.string "It's LORELEI of the ELITE FOUR!$"

gFameCheckerFlavorText_Lorelei3:: @ 0x81AED27
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Known for her logical, calculated,\n"
	.string "and cool battling style, LORELEI\l"
	.string "has a surprising secret!$"

gFameCheckerFlavorText_Lorelei4:: @ 0x81AEDAA
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Did you know that LORELEI has lots\n"
	.string "and lots of stuffed dolls?\p"
	.string "Every time she comes back to\n"
	.string "FOUR ISLAND, her collection grows!$"

gFameCheckerFlavorText_Lorelei5:: @ 0x81AEE51
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}The LAPRAS she has, I imagine it\n"
	.string "to be the one she met as a child.\p"
	.string "I believe it was in ICEFALL CAVE\n"
	.string "that she caught it.\p"
	.string "Perhaps that POKéMON has been with\n"
	.string "her ever since.$"

gFameCheckerFlavorText_Bruno0:: @ 0x81AEF25
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I am BRUNO of the ELITE FOUR!$"

gFameCheckerFlavorText_Bruno1:: @ 0x81AEF6C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I've lived and trained with my\n"
	.string "fighting POKéMON!$"

gFameCheckerFlavorText_Bruno2:: @ 0x81AEFC6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BRUNO apparently joined the ELITE\n"
	.string "FOUR out of his burning ambition to\l"
	.string "battle the best TRAINERS.$"

gFameCheckerFlavorText_Bruno3:: @ 0x81AF04C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BRUNO's my senior. He comes to the\n"
	.string "SPA to mend what training breaks.\p"
	.string "He tends his POKéMON's hurts\n"
	.string "before his own. Every time.$"

gFameCheckerFlavorText_Bruno4:: @ 0x81AF0F0
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}One of the ELITE FOUR came all\n"
	.string "this way for a RAGE CANDYBAR.\p"
	.string "Sold out. He just smiled, thanked\n"
	.string "us, and left. Not a flicker.$"

gFameCheckerFlavorText_Bruno5:: @ 0x81AF19A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Folk think BRUNO trains alone by\n"
	.string "creed.\p"
	.string "But he'll tell you every path has\n"
	.string "worth. He walked one with BRAWLY.$"

gFameCheckerFlavorText_Agatha0:: @ 0x81AF200
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I am AGATHA of the ELITE FOUR.$"

gFameCheckerFlavorText_Agatha1:: @ 0x81AF248
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}AGATHA's GHOST-type POKéMON are\n"
	.string "horrifically terrifying in toughness.$"

gFameCheckerFlavorText_Agatha2:: @ 0x81AF2B7
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}That old lady's got a short fuse.\p"
	.string "But beat her fair and she'll call\n"
	.string "you 'child' and mean it kindly.$"

gFameCheckerFlavorText_Agatha3:: @ 0x81AF34E
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}In her youth, AGATHA and PROF.\n"
	.string "OAK were rivals who vied for\l"
	.string "supremacy as TRAINERS.$"

gFameCheckerFlavorText_Agatha4:: @ 0x81AF3BE
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I hear OAK fusses over you, child.\p"
	.string "I knew him when he was tough.\n"
	.string "When he was DANGEROUS.\p"
	.string "Now he presses POKéMON into a book.\n"
	.string "…He chose that. I did not.$"

gFameCheckerFlavorText_Agatha5:: @ 0x81AF47C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}AGATHA set the record as the\n"
	.string "oldest-ever ELITE FOUR member.\p"
	.string "Fill a book with POKéMON? She'd\n"
	.string "sooner fill a battlefield.$"

gFameCheckerFlavorText_Lance0:: @ 0x81AF4FD
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I lead the ELITE FOUR.\p"
	.string "You can call me LANCE.\p"
	.string "…I like dragons.$"

gFameCheckerFlavorText_Lance1:: @ 0x81AF567
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Everything is a dragon, if you\n"
	.string "look closely enough.\p"
	.string "GYARADOS? A sea dragon.\n"
	.string "AERODACTYL? An ancient dragon.\p"
	.string "…You'll see it too. In time.$"

gFameCheckerFlavorText_Lance2:: @ 0x81AF641
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LANCE showed me my GYARADOS is\n"
	.string "a SEA DRAGON.\p"
	.string "Now I can't UNSEE it!\n"
	.string "He's the greatest, LANCE!$"

gFameCheckerFlavorText_Lance3:: @ 0x81AF6BA
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}We have a customer, LANCE, who\n"
	.string "occasionally comes.\p"
	.string "He always buys capes.\p"
	.string "I wonder… Does he have many\n"
	.string "identical capes at home?$"

gFameCheckerFlavorText_Lance4:: @ 0x81AF758
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LANCE's grandfather is thought to\n"
	.string "be the elder of a famous clan of\l"
	.string "dragon masters.$"

gFameCheckerFlavorText_Lance5:: @ 0x81AF7CB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LANCE has a cousin who leads a\n"
	.string "GYM far away. Same gift.\p"
	.string "Sees the dragon in everything.\n"
	.string "…It runs in the blood.$"

gFameCheckerFlavorText_Bill0:: @ 0x81AF83E
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}After all, BILL's world-famous as a\n"
	.string "POKéMANIAC.\p"
	.string "He invented the POKéMON Storage\n"
	.string "System on PC, too.$"

gFameCheckerFlavorText_Bill1:: @ 0x81AF8CA
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BILL has lots of POKéMON!\n"
	.string "He collects rare ones, too!$"

gFameCheckerFlavorText_Bill2:: @ 0x81AF929
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}He's my grandson!\p"
	.string "He always liked collecting things,\n"
	.string "even as a child!$"

gFameCheckerFlavorText_Bill3:: @ 0x81AF998
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BILL is a POKéMANIAC, so he loves\n"
	.string "every kind.\p"
	.string "Apparently, the first one he caught\n"
	.string "was an ABRA.$"

gFameCheckerFlavorText_Bill4:: @ 0x81AFA20
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BILL's hometown is GOLDENROD CITY,\n"
	.string "where his folks still live.\p"
	.string "I've heard that it's quite the\n"
	.string "festive, bustling city.$"

gFameCheckerFlavorText_Bill5:: @ 0x81AFAB9
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Apparently, BILL simply can't\n"
	.string "stomach milk at all.$"

gFameCheckerFlavorText_MrFuji0:: @ 0x81AFB0C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}He's really kind.\p"
	.string "He looks after abandoned and\n"
	.string "orphaned POKéMON.$"

gFameCheckerFlavorText_MrFuji1:: @ 0x81AFB76
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}This old guy marched right up to\n"
	.string "our HIDEOUT.\p"
	.string "Then, he starts ranting about how\n"
	.string "TEAM ROCKET's abusing POKéMON.\p"
	.string "So, we're just talking it over as\n"
	.string "adults.$"

gFameCheckerFlavorText_MrFuji2:: @ 0x81AFC38
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}POKéMON FAN MAGAZINE\n"
	.string "Monthly Grand Prize Drawing!\p"
	.string "The application form is…\p"
	.string "Gone! It's been clipped out.\n"
	.string "Someone must have applied already.$"

gFameCheckerFlavorText_MrFuji3:: @ 0x81AFCE9
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I hear that MR. FUJI's not from\n"
	.string "these parts originally, either.$"

gFameCheckerFlavorText_MrFuji4:: @ 0x81AFD49
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}It's a photo of BLAINE and\n"
	.string "MR. FUJI.\p"
	.string "They're standing shoulder to\n"
	.string "shoulder with big grins.$"

gFameCheckerFlavorText_MrFuji5:: @ 0x81AFDC4
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Editor: The shy MR. FUJI turned\n"
	.string "down our interview requests.\p"
	.string "He is a kindly man who is adored\n"
	.string "and respected in LAVENDER TOWN.$"

gFameCheckerFlavorText_Giovanni0:: @ 0x81AFE68
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I built TEAM ROCKET from nothing.\n"
	.string "Strong POKéMON built the rest.\p"
	.string "They are tools. I take the tools\n"
	.string "I need.\p"
	.string "I am the leader, GIOVANNI!$"

gFameCheckerFlavorText_Giovanni1:: @ 0x81AFF23
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Those thugs that took over our\n"
	.string "building…\p"
	.string "Their BOSS wanted only the\n"
	.string "strongest.\p"
	.string "A man from nothing trusts nothing\n"
	.string "but strength.$"

gFameCheckerFlavorText_Giovanni2:: @ 0x81AFFA8
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}TEAM ROCKET's BOSS is hard as\n"
	.string "stone.\p"
	.string "To him, POKéMON are tools…\n"
	.string "and so are people.$"

gFameCheckerFlavorText_Giovanni3:: @ 0x81B0022
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I have stood in VIRIDIAN all\n"
	.string "along.\p"
	.string "The LEADER no one ever met, while\n"
	.string "I built ROCKET up from nothing.$"

gFameCheckerFlavorText_Giovanni4:: @ 0x81B00A6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Blow me away! GIOVANNI, the ROCKET\n"
	.string "BOSS, was our GYM LEADER all along?$"

gFameCheckerFlavorText_Giovanni5:: @ 0x81B0106
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Family? Friends?\p"
	.string "That one came up from the gutter\n"
	.string "alone.\p"
	.string "If he needs anybody, no one has\n"
	.string "ever met them.$"


gFameCheckerPersonName_ProfOak:: @ 0x81B0188
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}PROF. OAK$"

gFameCheckerPersonQuote_ProfOak:: @ 0x81B0198
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: PROF. OAK\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Why do POKéMON compete and battle\n"
	.string "so hard for you?\p"
	.string "They do so because they can see\n"
	.string "the love and trust you have\l"
	.string "towards POKéMON.\p"
	.string "Never forget that.$"

gFameCheckerPersonName_Daisy:: @ 0x81B0251
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}DAISY$"

gFameCheckerPersonQuote_Daisy:: @ 0x81B025D
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: DAISY\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}While I was comfortably enjoying\n"
	.string "my tea breaks, you've grown very\l"
	.string "skilled and powerful.\p"
	.string "I hope you'll remain a good rival\n"
	.string "to my little brother.$"

gFameCheckerPersonName_Brock:: @ 0x81B030F
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}BROCK$"

gFameCheckerPersonQuote_Brock:: @ 0x81B031B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: BROCK\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}In this big world of ours, there\n"
	.string "must be many tough TRAINERS.\p"
	.string "Let's both keep training and\n"
	.string "making ourselves stronger!$"

gFameCheckerPersonName_Misty:: @ 0x81B03B3
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}MISTY$"

gFameCheckerPersonQuote_Misty:: @ 0x81B03BF
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: MISTY\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I'm going to keep training here at\n"
	.string "this GYM.\p"
	.string "When I get better, I'd love to hit\n"
	.string "the road and travel.$"

gFameCheckerPersonName_LtSurge:: @ 0x81B0446
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}LT. SURGE$"

gFameCheckerPersonQuote_LtSurge:: @ 0x81B0456
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: LT. SURGE\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Hey, kid!\n"
	.string "You electrified me in our battle!\p"
	.string "I didn't know that there were\n"
	.string "gutsy TRAINERS like you.\p"
	.string "It made me change my mind about\n"
	.string "you!$"

gFameCheckerPersonName_Erika:: @ 0x81B0504
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}ERIKA$"

gFameCheckerPersonQuote_Erika:: @ 0x81B0510
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: ERIKA\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I am so glad that there are strong\n"
	.string "TRAINERS like you.\p"
	.string "That awareness alone inspires and\n"
	.string "motivates me to try harder.\p"
	.string "Please visit me again.\n"
	.string "Zzz…$"

gFameCheckerPersonName_Koga:: @ 0x81B05C2
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}KOGA$"

gFameCheckerPersonQuote_Koga:: @ 0x81B05CD
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: KOGA\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}You and I, we must both set our\n"
	.string "sights higher and work towards\l"
	.string "meeting our challenges.\p"
	.string "Now, I must go train my daughter.$"

gFameCheckerPersonName_Sabrina:: @ 0x81B0667
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}SABRINA$"

gFameCheckerPersonQuote_Sabrina:: @ 0x81B0675
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: SABRINA\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}The love you have towards your\n"
	.string "POKéMON…\p"
	.string "It was a power that was never\n"
	.string "bested by my psychic power.$"

gFameCheckerPersonName_Blaine:: @ 0x81B06FB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}BLAINE$"

gFameCheckerPersonQuote_Blaine:: @ 0x81B0708
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: BLAINE\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}My fire POKéMON!\n"
	.string "They'll become even more powerful!\p"
	.string "And now, a quiz. How many kinds of\n"
	.string "FIRE-type POKéMON are there?$"

gFameCheckerPersonName_Lorelei:: @ 0x81B079F
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}LORELEI$"

gFameCheckerPersonQuote_Lorelei:: @ 0x81B07AD
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: LORELEI\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I needed to thank you for your\n"
	.string "help.\p"
	.string "But that has nothing to do with our\n"
	.string "battles.\p"
	.string "You'd better watch out next time!$"

gFameCheckerPersonName_Bruno:: @ 0x81B0845
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}BRUNO$"

gFameCheckerPersonQuote_Bruno:: @ 0x81B0851
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: BRUNO\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}The super power of your POKéMON\n"
	.string "and you I've experienced myself.\p"
	.string "Next time, maybe I should show you\n"
	.string "how to train yourself.$"

gFameCheckerPersonName_Agatha:: @ 0x81B08EE
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}AGATHA$"

gFameCheckerPersonQuote_Agatha:: @ 0x81B08FB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: AGATHA\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}When you grow older, don't you\n"
	.string "dare go soft like that coot OAK!\p"
	.string "Be like me and keep battling on!$"

gFameCheckerPersonName_Lance:: @ 0x81B097F
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}LANCE$"

gFameCheckerPersonQuote_Lance:: @ 0x81B098B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: LANCE\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I'm considering going back to my\n"
	.string "hometown.\p"
	.string "I want to retrain my DRAGON-type\n"
	.string "POKéMON and strengthen them.\p"
	.string "I'd like to invite you to my\n"
	.string "hometown one day.$"

gFameCheckerPersonName_Bill:: @ 0x81B0A45
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}BILL$"

gFameCheckerPersonQuote_Bill:: @ 0x81B0A50
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: BILL\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Hey, there! CELIO had nothing but\n"
	.string "praise for you.\p"
	.string "Hearing that makes me happy.\p"
	.string "When you catch some rare POKéMON,\n"
	.string "come show me, okay? Promise!$"

gFameCheckerPersonName_MrFuji:: @ 0x81B0AFF
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}MR. FUJI$"

gFameCheckerPersonQuote_MrFuji:: @ 0x81B0B0E
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: MR. FUJI\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Instead of hoping for the happiness\n"
	.string "of just your POKéMON…\p"
	.string "…Can I get you to wish for the\n"
	.string "happiness of all POKéMON?$"

gFameCheckerPersonName_Giovanni:: @ 0x81B0BA6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}GIOVANNI$"

gFameCheckerPersonQuote_Giovanni:: @ 0x81B0BB5
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: GIOVANNI\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I have nothing to say to a child.\p"
	.string "Only this. I go back to the dirt\n"
	.string "I came from…\p"
	.string "to make myself stronger. Alone,\n"
	.string "as I began.$"

gFameCheckerFlavorTextOriginLocation_ProfOak0:: @ 0x81B0C45
	.string "PALLET TOWN$"

gFameCheckerFlavorTextOriginLocation_ProfOak1::
	.string "RESEARCH LAB$"

gFameCheckerFlavorTextOriginLocation_ProfOak2::
	.string "RESEARCH LAB$"

gFameCheckerFlavorTextOriginLocation_ProfOak3::
	.string "VIRIDIAN CITY$"

gFameCheckerFlavorTextOriginLocation_ProfOak4::
	.string "POKéMON LEAGUE$"

gFameCheckerFlavorTextOriginLocation_ProfOak5::
	.string "RESEARCH LAB$"

gFameCheckerFlavorTextOriginLocation_Daisy0::
	.string "RESEARCH LAB$"

gFameCheckerFlavorTextOriginLocation_Daisy1::
	.string "VERMILION CITY$"

gFameCheckerFlavorTextOriginLocation_Daisy2::
	.string "WATER LABYRINTH$"

gFameCheckerFlavorTextOriginLocation_Daisy3::
	.string "VIRIDIAN CITY$"

gFameCheckerFlavorTextOriginLocation_Daisy4::
	.string "CELADON MANSION$"

gFameCheckerFlavorTextOriginLocation_Daisy5::
	.string "FOUR ISLAND$"

gFameCheckerFlavorTextOriginLocation_Brock0::
	.string "PEWTER CITY$"

gFameCheckerFlavorTextOriginLocation_Brock1::
	.string "PEWTER GYM$"

gFameCheckerFlavorTextOriginLocation_Brock2::
	.string "PEWTER CITY$"

gFameCheckerFlavorTextOriginLocation_Brock3::
	.string "ROUTE 4$"

gFameCheckerFlavorTextOriginLocation_Brock4::
	.string "MT. MOON$"

gFameCheckerFlavorTextOriginLocation_Brock5::
	.string "PEWTER MUSEUM$"

gFameCheckerFlavorTextOriginLocation_Misty0::
	.string "CERULEAN CITY$"

gFameCheckerFlavorTextOriginLocation_Misty1::
	.string "CERULEAN GYM$"

gFameCheckerFlavorTextOriginLocation_Misty2::
	.string "CERULEAN GYM$"

gFameCheckerFlavorTextOriginLocation_Misty3::
	.string "SEAFOAM ISLANDS$"

gFameCheckerFlavorTextOriginLocation_Misty4::
	.string "CERULEAN CAPE$"

gFameCheckerFlavorTextOriginLocation_Misty5::
	.string "CERULEAN CITY$"

gFameCheckerFlavorTextOriginLocation_LtSurge0::
	.string "VERMILION CITY$"

gFameCheckerFlavorTextOriginLocation_LtSurge1::
	.string "VERMILION GYM$"

gFameCheckerFlavorTextOriginLocation_LtSurge2::
	.string "VERMILION GYM$"

gFameCheckerFlavorTextOriginLocation_LtSurge3::
	.string "VERMILION GYM$"

gFameCheckerFlavorTextOriginLocation_LtSurge4::
	.string "VERMILION GYM$"

gFameCheckerFlavorTextOriginLocation_LtSurge5::
	.string "VERMILION CITY$"

gFameCheckerFlavorTextOriginLocation_Erika0::
	.string "CELADON CITY$"

gFameCheckerFlavorTextOriginLocation_Erika1::
	.string "CELADON GYM$"

gFameCheckerFlavorTextOriginLocation_Erika2::
	.string "CELADON GYM$"

gFameCheckerFlavorTextOriginLocation_Erika3::
	.string "CELADON GYM$"

gFameCheckerFlavorTextOriginLocation_Erika4::
	.string "CELADON GYM$"

gFameCheckerFlavorTextOriginLocation_Erika5::
	.string "CELADON MANSION$"

gFameCheckerFlavorTextOriginLocation_Koga0::
	.string "FUCHSIA CITY$"

gFameCheckerFlavorTextOriginLocation_Koga1::
	.string "FUCHSIA GYM$"

gFameCheckerFlavorTextOriginLocation_Koga2::
	.string "FUCHSIA GYM$"

gFameCheckerFlavorTextOriginLocation_Koga3::
	.string "FUCHSIA CITY$"

gFameCheckerFlavorTextOriginLocation_Koga4::
	.string "FUCHSIA CITY$"

gFameCheckerFlavorTextOriginLocation_Koga5::
	.string "SAFARI ZONE$"

gFameCheckerFlavorTextOriginLocation_Sabrina0::
	.string "SAFFRON CITY$"

gFameCheckerFlavorTextOriginLocation_Sabrina1::
	.string "THREE ISLAND$"

gFameCheckerFlavorTextOriginLocation_Sabrina2::
	.string "SAFFRON GYM$"

gFameCheckerFlavorTextOriginLocation_Sabrina3::
	.string "SAFFRON GYM$"

gFameCheckerFlavorTextOriginLocation_Sabrina4::
	.string "SAFFRON CITY$"

gFameCheckerFlavorTextOriginLocation_Sabrina5::
	.string "SAFFRON GYM$"

gFameCheckerFlavorTextOriginLocation_Blaine0::
	.string "CINNABAR ISLAND$"

gFameCheckerFlavorTextOriginLocation_Blaine1::
	.string "CINNABAR GYM$"

gFameCheckerFlavorTextOriginLocation_Blaine2::
	.string "CINNABAR GYM$"

gFameCheckerFlavorTextOriginLocation_Blaine3::
	.string "CINNABAR ISLAND$"

gFameCheckerFlavorTextOriginLocation_Blaine4::
	.string "CINNABAR GYM$"

gFameCheckerFlavorTextOriginLocation_Blaine5::
	.string "RESORT GORGEOUS$"

gFameCheckerFlavorTextOriginLocation_Lorelei0::
	.string "POKéMON LEAGUE$"

gFameCheckerFlavorTextOriginLocation_Lorelei1::
	.string "POKéMON LEAGUE$"

gFameCheckerFlavorTextOriginLocation_Lorelei2::
	.string "FOUR ISLAND$"

gFameCheckerFlavorTextOriginLocation_Lorelei3::
	.string "FIVE ISLAND$"

gFameCheckerFlavorTextOriginLocation_Lorelei4::
	.string "FOUR ISLAND$"

gFameCheckerFlavorTextOriginLocation_Lorelei5::
	.string "FOUR ISLAND$"

gFameCheckerFlavorTextOriginLocation_Bruno0::
	.string "POKéMON LEAGUE$"

gFameCheckerFlavorTextOriginLocation_Bruno1::
	.string "POKéMON LEAGUE$"

gFameCheckerFlavorTextOriginLocation_Bruno2::
	.string "SAFFRON CITY$"

gFameCheckerFlavorTextOriginLocation_Bruno3::
	.string "EMBER SPA$"

gFameCheckerFlavorTextOriginLocation_Bruno4::
	.string "TWO ISLAND$"

gFameCheckerFlavorTextOriginLocation_Bruno5::
	.string "SEVAULT CANYON$"

gFameCheckerFlavorTextOriginLocation_Agatha0::
	.string "POKéMON LEAGUE$"

gFameCheckerFlavorTextOriginLocation_Agatha1::
	.string "INDIGO PLATEAU$"

gFameCheckerFlavorTextOriginLocation_Agatha2::
	.string "INDIGO PLATEAU$"

gFameCheckerFlavorTextOriginLocation_Agatha3::
	.string "SEVEN ISLAND$"

gFameCheckerFlavorTextOriginLocation_Agatha4::
	.string "POKéMON LEAGUE$"

gFameCheckerFlavorTextOriginLocation_Agatha5::
	.string "SIX ISLAND$"

gFameCheckerFlavorTextOriginLocation_Lance0::
	.string "POKéMON LEAGUE$"

gFameCheckerFlavorTextOriginLocation_Lance1::
	.string "POKéMON LEAGUE$"

gFameCheckerFlavorTextOriginLocation_Lance2::
	.string "SAFFRON CITY$"

gFameCheckerFlavorTextOriginLocation_Lance3::
	.string "CELADON DEPT.$"

gFameCheckerFlavorTextOriginLocation_Lance4::
	.string "INDIGO PLATEAU$"

gFameCheckerFlavorTextOriginLocation_Lance5::
	.string "INDIGO PLATEAU$"

gFameCheckerFlavorTextOriginLocation_Bill0::
	.string "CERULEAN CITY$"

gFameCheckerFlavorTextOriginLocation_Bill1::
	.string "CERULEAN CITY$"

gFameCheckerFlavorTextOriginLocation_Bill2::
	.string "FUCHSIA CITY$"

gFameCheckerFlavorTextOriginLocation_Bill3::
	.string "ONE ISLAND$"

gFameCheckerFlavorTextOriginLocation_Bill4::
	.string "ONE ISLAND$"

gFameCheckerFlavorTextOriginLocation_Bill5::
	.string "ONE ISLAND$"

gFameCheckerFlavorTextOriginLocation_MrFuji0::
	.string "LAVENDER TOWN$"

gFameCheckerFlavorTextOriginLocation_MrFuji1::
	.string "POKéMON TOWER$"

gFameCheckerFlavorTextOriginLocation_MrFuji2::
	.string "LAVENDER TOWN$"

gFameCheckerFlavorTextOriginLocation_MrFuji3::
	.string "LAVENDER TOWN$"

gFameCheckerFlavorTextOriginLocation_MrFuji4::
	.string "CINNABAR GYM$"

gFameCheckerFlavorTextOriginLocation_MrFuji5::
	.string "CINNABAR ISLAND$"

gFameCheckerFlavorTextOriginLocation_Giovanni0::
	.string "ROCKET HIDEOUT$"

gFameCheckerFlavorTextOriginLocation_Giovanni1::
	.string "SILPH CO.$"

gFameCheckerFlavorTextOriginLocation_Giovanni2::
	.string "SILPH CO.$"

gFameCheckerFlavorTextOriginLocation_Giovanni3::
	.string "VIRIDIAN GYM$"

gFameCheckerFlavorTextOriginLocation_Giovanni4::
	.string "VIRIDIAN GYM$"

gFameCheckerFlavorTextOriginLocation_Giovanni5::
	.string "ROCKET WAREHOUSE$"

gFameCheckerFlavorTextOriginObjectName_ProfOak0::
	.string "SIGN$"

gFameCheckerFlavorTextOriginObjectName_ProfOak1::
	.string "PROF. OAK$"

gFameCheckerFlavorTextOriginObjectName_ProfOak2::
	.string "AIDE$"

gFameCheckerFlavorTextOriginObjectName_ProfOak3::
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_ProfOak4::
	.string "AGATHA$"

gFameCheckerFlavorTextOriginObjectName_ProfOak5::
	.string "AIDE$"

gFameCheckerFlavorTextOriginObjectName_Daisy0::
	.string "AIDE$"

gFameCheckerFlavorTextOriginObjectName_Daisy1::
	.string "WOMAN$"

gFameCheckerFlavorTextOriginObjectName_Daisy2::
	.string "MAN$"

gFameCheckerFlavorTextOriginObjectName_Daisy3::
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Daisy4::
	.string "OLD LADY$"

gFameCheckerFlavorTextOriginObjectName_Daisy5::
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Brock0::
	.string "SIGN$"

gFameCheckerFlavorTextOriginObjectName_Brock1::
	.string "BROCK$"

gFameCheckerFlavorTextOriginObjectName_Brock2::
	.string "YOUNG MAN$"

gFameCheckerFlavorTextOriginObjectName_Brock3::
	.string "BOY$"

gFameCheckerFlavorTextOriginObjectName_Brock4::
	.string "MAN$"

gFameCheckerFlavorTextOriginObjectName_Brock5::
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Misty0::
	.string "SIGN$"

gFameCheckerFlavorTextOriginObjectName_Misty1::
	.string "MISTY$"

gFameCheckerFlavorTextOriginObjectName_Misty2::
	.string "LUIS$"

gFameCheckerFlavorTextOriginObjectName_Misty3::
	.string "YOUNG MAN$"

gFameCheckerFlavorTextOriginObjectName_Misty4::
	.string "DAME$"

gFameCheckerFlavorTextOriginObjectName_Misty5::
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_LtSurge0::
	.string "SIGN$"

gFameCheckerFlavorTextOriginObjectName_LtSurge1::
	.string "LT. SURGE$"

gFameCheckerFlavorTextOriginObjectName_LtSurge2::
	.string "TUCKER$"

gFameCheckerFlavorTextOriginObjectName_LtSurge3::
	.string "TUCKER$"

gFameCheckerFlavorTextOriginObjectName_LtSurge4::
	.string "DWAYNE$"

gFameCheckerFlavorTextOriginObjectName_LtSurge5::
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Erika0::
	.string "SIGN$"

gFameCheckerFlavorTextOriginObjectName_Erika1::
	.string "ERIKA$"

gFameCheckerFlavorTextOriginObjectName_Erika2::
	.string "LOLA$"

gFameCheckerFlavorTextOriginObjectName_Erika3::
	.string "TAMIA$"

gFameCheckerFlavorTextOriginObjectName_Erika4::
	.string "ERIKA$"

gFameCheckerFlavorTextOriginObjectName_Erika5::
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Koga0::
	.string "SIGN$"

gFameCheckerFlavorTextOriginObjectName_Koga1::
	.string "KOGA$"

gFameCheckerFlavorTextOriginObjectName_Koga2::
	.string "KIRK$"

gFameCheckerFlavorTextOriginObjectName_Koga3::
	.string "CHARINE$"

gFameCheckerFlavorTextOriginObjectName_Koga4::
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Koga5::
	.string "MAN$"

gFameCheckerFlavorTextOriginObjectName_Sabrina0::
	.string "SIGN$"

gFameCheckerFlavorTextOriginObjectName_Sabrina1::
	.string "YOUNG MAN$"

gFameCheckerFlavorTextOriginObjectName_Sabrina2::
	.string "SABRINA$"

gFameCheckerFlavorTextOriginObjectName_Sabrina3::
	.string "SABRINA$"

gFameCheckerFlavorTextOriginObjectName_Sabrina4::
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Sabrina5::
	.string "TYRON$"

gFameCheckerFlavorTextOriginObjectName_Blaine0::
	.string "SIGN$"

gFameCheckerFlavorTextOriginObjectName_Blaine1::
	.string "BLAINE$"

gFameCheckerFlavorTextOriginObjectName_Blaine2::
	.string "DEREK$"

gFameCheckerFlavorTextOriginObjectName_Blaine3::
	.string "WOMAN$"

gFameCheckerFlavorTextOriginObjectName_Blaine4::
	.string "PHOTO$"

gFameCheckerFlavorTextOriginObjectName_Blaine5::
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Lorelei0::
	.string "LORELEI$"

gFameCheckerFlavorTextOriginObjectName_Lorelei1::
	.string "LORELEI$"

gFameCheckerFlavorTextOriginObjectName_Lorelei2::
	.string "OLD MAN$"

gFameCheckerFlavorTextOriginObjectName_Lorelei3::
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Lorelei4::
	.string "LITTLE GIRL$"

gFameCheckerFlavorTextOriginObjectName_Lorelei5::
	.string "OLD LADY$"

gFameCheckerFlavorTextOriginObjectName_Bruno0::
	.string "BRUNO$"

gFameCheckerFlavorTextOriginObjectName_Bruno1::
	.string "BRUNO$"

gFameCheckerFlavorTextOriginObjectName_Bruno2::
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Bruno3::
	.string "CRUSHER$"

gFameCheckerFlavorTextOriginObjectName_Bruno4::
	.string "WOMAN$"

gFameCheckerFlavorTextOriginObjectName_Bruno5::
	.string "CRUSHER$"

gFameCheckerFlavorTextOriginObjectName_Agatha0::
	.string "AGATHA$"

gFameCheckerFlavorTextOriginObjectName_Agatha1::
	.string "CRUSHER$"

gFameCheckerFlavorTextOriginObjectName_Agatha2::
	.string "CRUSHER$"

gFameCheckerFlavorTextOriginObjectName_Agatha3::
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Agatha4::
	.string "AGATHA$"

gFameCheckerFlavorTextOriginObjectName_Agatha5::
	.string "OLD LADY$"

gFameCheckerFlavorTextOriginObjectName_Lance0::
	.string "LANCE$"

gFameCheckerFlavorTextOriginObjectName_Lance1::
	.string "LANCE$"

gFameCheckerFlavorTextOriginObjectName_Lance2::
	.string "WOMAN$"

gFameCheckerFlavorTextOriginObjectName_Lance3::
	.string "LITTLE GIRL$"

gFameCheckerFlavorTextOriginObjectName_Lance4::
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Lance5::
	.string "YOUNG MAN$"

gFameCheckerFlavorTextOriginObjectName_Bill0::
	.string "{RIVAL}$"

gFameCheckerFlavorTextOriginObjectName_Bill1::
	.string "LITTLE BOY$"

gFameCheckerFlavorTextOriginObjectName_Bill2::
	.string "OLD MAN$"

gFameCheckerFlavorTextOriginObjectName_Bill3::
	.string "CELIO$"

gFameCheckerFlavorTextOriginObjectName_Bill4::
	.string "CELIO$"

gFameCheckerFlavorTextOriginObjectName_Bill5::
	.string "CELIO$"

gFameCheckerFlavorTextOriginObjectName_MrFuji0::
	.string "LITTLE GIRL$"

gFameCheckerFlavorTextOriginObjectName_MrFuji1::
	.string "TEAM ROCKET$"

gFameCheckerFlavorTextOriginObjectName_MrFuji2::
	.string "MAGAZINE$"

gFameCheckerFlavorTextOriginObjectName_MrFuji3::
	.string "MAN$"

gFameCheckerFlavorTextOriginObjectName_MrFuji4::
	.string "PHOTO$"

gFameCheckerFlavorTextOriginObjectName_MrFuji5::
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Giovanni0::
	.string "GIOVANNI$"

gFameCheckerFlavorTextOriginObjectName_Giovanni1::
	.string "SCIENTIST$"

gFameCheckerFlavorTextOriginObjectName_Giovanni2::
	.string "SCIENTIST$"

gFameCheckerFlavorTextOriginObjectName_Giovanni3::
	.string "GIOVANNI$"

gFameCheckerFlavorTextOriginObjectName_Giovanni4::
	.string "MAN$"

gFameCheckerFlavorTextOriginObjectName_Giovanni5::
	.string "GIDEON$"

PokemonJournal_Text_SpecialFeatureBrock::
	.string "POKéMON JOURNAL\p"
	.string "Special Feature: PEWTER GYM\n"
	.string "LEADER BROCK!\p"
	.string "BROCK rarely laughs, but is said to\n"
	.string "be unable to stop if he starts.$"

PokemonJournal_Text_SpecialFeatureMisty::
	.string "POKéMON JOURNAL\p"
	.string "Special Feature: CERULEAN GYM\n"
	.string "LEADER MISTY!\p"
	.string "MISTY is said to worship LORELEI\n"
	.string "of the ELITE FOUR.$"

PokemonJournal_Text_SpecialFeatureLtSurge::
	.string "POKéMON JOURNAL\p"
	.string "Special Feature: VERMILION GYM\n"
	.string "LEADER LT. SURGE!\p"
	.string "LT. SURGE is rumored to have been\n"
	.string "a pilot while home in America.\p"
	.string "He used the electricity generated\n"
	.string "by POKéMON to power his plane.$"

PokemonJournal_Text_SpecialFeatureErika::
	.string "POKéMON JOURNAL\p"
	.string "Special Feature: CELADON GYM\n"
	.string "LEADER ERIKA!\p"
	.string "Rumor has it that if you peek into\n"
	.string "CELADON GYM, you can often\l"
	.string "see ERIKA snoozing.$"

PokemonJournal_Text_SpecialFeatureKoga::
	.string "POKéMON JOURNAL\p"
	.string "Special Feature: FUCHSIA GYM\n"
	.string "LEADER KOGA!\p"
	.string "KOGA is said to have a thorough\n"
	.string "knowledge of medicine.\p"
	.string "He even concocts medicine to nurse\n"
	.string "his POKéMON to health.$"

PokemonJournal_Text_SpecialFeatureSabrina::
	.string "POKéMON JOURNAL\p"
	.string "Special Feature: SAFFRON GYM\n"
	.string "LEADER SABRINA!\p"
	.string "People say that SABRINA can\n"
	.string "communicate with her POKéMON\l"
	.string "during battle without speaking.$"

PokemonJournal_Text_SpecialFeatureBlaine::
	.string "POKéMON JOURNAL\p"
	.string "Special Feature: CINNABAR GYM\n"
	.string "LEADER BLAINE!\p"
	.string "BLAINE is said to remove his dark\n"
	.string "shades only when he is thinking up\l"
	.string "new quiz questions.$"

PokemonJournal_Text_SpecialFeatureLorelei::
	.string "POKéMON JOURNAL\p"
	.string "Special Feature:\n"
	.string "ELITE FOUR's LORELEI!\p"
	.string "Known for her logical, calculated,\n"
	.string "and cool battling style, LORELEI\l"
	.string "has a surprising secret!$"

PokemonJournal_Text_SpecialFeatureBruno::
	.string "POKéMON JOURNAL\p"
	.string "Special Feature:\n"
	.string "ELITE FOUR's BRUNO!\p"
	.string "BRUNO apparently joined the ELITE\n"
	.string "FOUR out of his burning ambition to\l"
	.string "battle the best TRAINERS.$"

PokemonJournal_Text_SpecialFeatureAgatha::
	.string "POKéMON JOURNAL\p"
	.string "Special Feature:\n"
	.string "ELITE FOUR's AGATHA!\p"
	.string "In her youth, AGATHA and PROF.\n"
	.string "OAK were rivals who vied for\l"
	.string "supremacy as TRAINERS.$"

PokemonJournal_Text_SpecialFeatureLance::
	.string "POKéMON JOURNAL\p"
	.string "Special Feature:\n"
	.string "ELITE FOUR's LANCE!\p"
	.string "LANCE's grandfather is thought to\n"
	.string "be the elder of a famous clan of\l"
	.string "dragon masters.$"

PokemonJournal_Text_SpecialFeatureProfOak::
	.string "POKéMON JOURNAL\p"
	.string "Special Feature: PROF. OAK,\n"
	.string "the POKéMON Researcher!\p"
	.string "PROF. OAK reportedly lives with his\n"
	.string "grandchildren DAISY and {RIVAL}.$"

PokemonJournal_Text_SpecialFeatureDaisyOak::
	.string "This is a POKéMON JOURNAL from\n"
	.string "years ago…\p"
	.string "POKéMON JOURNAL\n"
	.string "CONTEST Special!\p"
	.string "The Spring POKéMON CONTEST's\n"
	.string "Grand Champion is DAISY OAK of\l"
	.string "PALLET TOWN!$"

PokemonJournal_Text_SpecialFeatureMrFuji::
	.string "POKéMON JOURNAL\p"
	.string "Special Feature:\n"
	.string "MR. FUJI of POKéMON HOUSE!\p"
	.string "Editor: The shy MR. FUJI turned\n"
	.string "down our interview requests.\p"
	.string "He is a kindly man who is adored\n"
	.string "and respected in LAVENDER TOWN.$"
