SSAnne_1F_Corridor_Frlg_MapScripts::
	.byte 0

SSAnne_1F_Corridor_EventScript_WorkerM::
	msgbox SSAnne_1F_Corridor_Text_LeStrongSilentType, MSGBOX_NPC
	end

SSAnne_1F_Corridor_EventScript_Sailor::
	msgbox SSAnne_1F_Corridor_Text_PassengersAreRestless, MSGBOX_NPC
	end

SSAnne_1F_Corridor_Text_LeStrongSilentType::
	.string "Bonjour!\n"
	.string "I am le waiter on this ship!\p"
	.string "She runs proud these days, non?\n"
	.string "Was not always a ship to serve on.\p"
	.string "… … …\n"
	.string "Ah. You ask no more. Tres bien.$"

SSAnne_1F_Corridor_Text_PassengersAreRestless::
	.string "The passengers are restless from\n"
	.string "this long voyage.\p"
	.string "You might be challenged by the\n"
	.string "more bored ones!\p"
	.string "Grand, isn't she? Sails clean out\n"
	.string "of VERMILION, free as you please.\p"
	.string "Wasn't always so.\n"
	.string "…You're too young to know it.$"

