UndergroundPath_WestEntrance_Frlg_MapScripts::
	.byte 0

UndergroundPath_WestEntrance_EventScript_BaldingMan::
	msgbox UndergroundPath_WestEntrance_Text_SleepyMonNearCeladon, MSGBOX_NPC
	end

UndergroundPath_WestEntrance_Text_SleepyMonNearCeladon::
	.string "They all flick a coin in the\n"
	.string "drain before they cross under.\p"
	.string "I never have. Not once.\p"
	.string "…Still here, aren't I. Still got\n"
	.string "all my coins, too.$"

