SSAnne_2F_Room6_Frlg_MapScripts::
	.byte 0

SSAnne_2F_Room6_EventScript_Woman1::
	msgbox SSAnne_2F_Room6_Text_CaptainIsAwfullySick, MSGBOX_NPC
	end

SSAnne_2F_Room6_EventScript_Woman2::
	msgbox SSAnne_2F_Room6_Text_ManyPeopleGetSeasick, MSGBOX_NPC
	end

SSAnne_2F_Room6_Text_CaptainIsAwfullySick::
	.string "The CAPTAIN looked awfully pale.\p"
	.string "He keeps to his cabin now.\n"
	.string "Tired, they say.\p"
	.string "…Some tired doesn't come from work.$"

SSAnne_2F_Room6_Text_ManyPeopleGetSeasick::
	.string "I hear many people get seasick.$"

