SafariZone_East_RestHouse_Frlg_MapScripts::
	.byte 0

SafariZone_East_RestHouse_EventScript_Rocker::
	msgbox SafariZone_East_Text_CaughtChanseyAllWorthwhile, MSGBOX_NPC
	end

SafariZone_East_RestHouse_EventScript_Scientist::
	msgbox SafariZone_East_Text_HowManyDidYouCatch, MSGBOX_NPC
	end

SafariZone_East_RestHouse_EventScript_BaldingMan::
	msgbox SafariZone_East_Text_TiredFromAllTheFun, MSGBOX_NPC
	end

SafariZone_East_Text_HowManyDidYouCatch::
	.string "How many did you bag?\p"
	.string "This place takes more legs\n"
	.string "than luck.$"

SafariZone_East_Text_CaughtChanseyAllWorthwhile::
	.string "A CHANSEY. I actually caught\n"
	.string "one.\p"
	.string "Worth the whole week.$"

SafariZone_East_Text_TiredFromAllTheFun::
	.string "Whew…\n"
	.string "Some chase, that.$"

