SafariZone_Center_RestHouse_Frlg_MapScripts::
	.byte 0

SafariZone_Center_RestHouse_EventScript_Sara::
	msgbox SafariZone_Center_Text_WhereDidErikGo, MSGBOX_NPC
	end

SafariZone_Center_RestHouse_EventScript_Scientist::
	msgbox SafariZone_Center_Text_CatchingMonsAsGifts, MSGBOX_NPC
	end

SafariZone_Center_Text_WhereDidErikGo::
	.string "SARA: Where did my boyfriend,\n"
	.string "ERIK, go?$"

SafariZone_Center_Text_CatchingMonsAsGifts::
	.string "Catching a few to take home\n"
	.string "as gifts.\p"
	.string "The niece asked for one that\n"
	.string "breathes fire.$"

