PewterCity_Museum_2F_Frlg_MapScripts::
	.byte 0

PewterCity_Museum_2F_EventScript_Man::
	msgbox PewterCity_Museum_1F_Text_WhatsSpecialAboutMoonStone, MSGBOX_NPC
	end

PewterCity_Museum_2F_EventScript_OldMan::
	msgbox PewterCity_Museum_1F_Text_BoughtColorTVForMoonLanding, MSGBOX_NPC
	end

PewterCity_Museum_2F_EventScript_Scientist::
	msgbox PewterCity_Museum_1F_Text_RunningSpaceExhibitThisMonth, MSGBOX_NPC
	end

PewterCity_Museum_2F_EventScript_LittleGirl::
	msgbox PewterCity_Museum_1F_Text_AskedDaddyToCatchPikachu, MSGBOX_NPC
	end

PewterCity_Museum_2F_EventScript_BaldingMan::
	msgbox PewterCity_Museum_1F_Text_PikachuSoonIPromise, MSGBOX_NPC
	end

PewterCity_Museum_2F_EventScript_SpaceShuttle::
	msgbox PewterCity_Museum_1F_Text_SpaceShuttle, MSGBOX_SIGN
	end

PewterCity_Museum_2F_EventScript_MoonStone::
	msgbox PewterCity_Museum_1F_Text_MeteoriteThatFellOnMtMoon, MSGBOX_SIGN
	end

Text_SeismicTossTeach::
	.string "The secrets of space…\n"
	.string "The mysteries of earth…\p"
	.string "There are so many things about\n"
	.string "which we know so little.\p"
	.string "But that should spur us to study\n"
	.string "harder, not toss in the towel.\p"
	.string "The only thing you should toss…\p"
	.string "Well, how about SEISMIC TOSS?\n"
	.string "Should I teach that to a POKéMON?$"

Text_SeismicTossDeclined::
	.string "Is that so?\n"
	.string "I'm sure you'll be back for it.$"

Text_SeismicTossWhichMon::
	.string "Which POKéMON wants to learn\n"
	.string "SEISMIC TOSS?$"

Text_SeismicTossTaught::
	.string "I hope you won't toss in the towel.\n"
	.string "Keep it up.$"

PewterCity_Museum_1F_Text_WhatsSpecialAboutMoonStone::
	.string "Looks like a plain rock to you.\p"
	.string "There's harder stone in PEWTER\n"
	.string "than anything in this case.\p"
	.string "…Wears a GYM LEADER's face.$"

PewterCity_Museum_1F_Text_BoughtColorTVForMoonLanding::
	.string "Back when I was young, one phone\n"
	.string "in a house was a marvel.\p"
	.string "You should see the wall of them\n"
	.string "at the GYM now. …All ringing.$"

PewterCity_Museum_1F_Text_RunningSpaceExhibitThisMonth::
	.string "This month, we're running a space\n"
	.string "exhibit.$"

PewterCity_Museum_1F_Text_AskedDaddyToCatchPikachu::
	.string "When I'm big I'll go to CERULEAN\n"
	.string "and only keep WATER POKéMON.\p"
	.string "There's a girl there who does.\n"
	.string "…I don't know why. I just like it.$"

PewterCity_Museum_1F_Text_PikachuSoonIPromise::
	.string "A PIKACHU soon, pumpkin, promise.\p"
	.string "…BROCK caught one for a child\n"
	.string "once. Took no thanks for it.$"

PewterCity_Museum_1F_Text_SpaceShuttle::
	.string "Space Shuttle$"

PewterCity_Museum_1F_Text_MeteoriteThatFellOnMtMoon::
	.string "A meteorite that fell on MT. MOON.\n"
	.string "It is thought to be a MOON STONE.$"

