SSAnne_2F_Room3_Frlg_MapScripts::
	.byte 0

SSAnne_2F_Room3_EventScript_Gentleman::
	msgbox SSAnne_2F_Room3_Text_SeenMonsFerryPeople, MSGBOX_NPC
	end

SSAnne_2F_Room3_EventScript_OldMan::
	msgbox SSAnne_2F_Room3_Text_SomeTreesCanBeCutDown, MSGBOX_NPC
	end

SSAnne_2F_Room3_Text_SeenMonsFerryPeople::
	.string "Old sailors tell of a trainer with\n"
	.string "an empty belt.\p"
	.string "Crossed all of KANTO, they say,\n"
	.string "and never caught a single one.\p"
	.string "The wild ones followed him anyway.\n"
	.string "Even bore him over the water.$"

SSAnne_2F_Room3_Text_SomeTreesCanBeCutDown::
	.string "Small trees can be chopped down\n"
	.string "using the move CUT.\p"
	.string "But remember this!\n"
	.string "CUT is an HM technique.\p"
	.string "Once learned, it is not so easily\n"
	.string "discarded.$"

