SafariZone_North_RestHouse_Frlg_MapScripts::
	.byte 0

SafariZone_North_RestHouse_EventScript_Fisher::
	msgbox SafariZone_East_Text_PrizeInDeepestPartOfSafariZone, MSGBOX_NPC
	end

SafariZone_North_RestHouse_EventScript_Scientist::
	msgbox SafariZone_East_Text_KeepAnyItemFoundOnSafari, MSGBOX_NPC
	end

SafariZone_North_RestHouse_EventScript_Gentleman::
	msgbox SafariZone_East_Text_MyEeveeEvolvedIntoFlareon, MSGBOX_NPC
	end

SafariZone_East_Text_KeepAnyItemFoundOnSafari::
	.string "Any item you find here is\n"
	.string "yours to keep.\p"
	.string "Chase them all and the clock\n"
	.string "beats you.$"

SafariZone_East_Text_PrizeInDeepestPartOfSafariZone::
	.string "Deepest part of the ZONE,\n"
	.string "they say, a prize.\p"
	.string "Every pond out here stops me\n"
	.string "short.$"

SafariZone_East_Text_MyEeveeEvolvedIntoFlareon::
	.string "My EEVEE became a JOLTEON.\p"
	.string "My neighbor's, a VAPOREON.\n"
	.string "Same litter…$"

