UndergroundPath_SouthEntrance_Frlg_MapScripts::
	.byte 0

UndergroundPath_SouthEntrance_EventScript_Woman::
	msgbox UndergroundPath_SouthEntrance_Text_PeopleLoseThingsInTheDarkness, MSGBOX_NPC
	end

UndergroundPath_SouthEntrance_Text_PeopleLoseThingsInTheDarkness::
	.string "Flick a coin down the drain\n"
	.string "before you go under. Everyone does.\p"
	.string "Why? …You just do, dear.\p"
	.string "And don't ask what happens if you\n"
	.string "don't. Only mind that you do it.$"

