DiglettsCave_SouthEntrance_Frlg_MapScripts::
	.byte 0

DiglettsCave_SouthEntrance_EventScript_OldMan::
	msgbox DiglettsCave_SouthEntrance_Text_DiglettDugThisTunnel, MSGBOX_NPC
	end

DiglettsCave_SouthEntrance_Text_DiglettDugThisTunnel::
	.string "Feel that draft on your neck?\n"
	.string "DIGLETT bored this whole tunnel.\p"
	.string "Comes out clear at VIRIDIAN, so\n"
	.string "they swear. I've never dared it.$"

